import { getCurrentUser, json } from "../../_shared/auth.js";
function id(prefix){const b=new Uint8Array(16);crypto.getRandomValues(b);return `${prefix}_${[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}`;}
async function member(env,s,u){return env.DB.prepare(`SELECT role FROM server_members WHERE server_id=? AND user_id=?`).bind(s,u).first();}
function cleanName(v){return String(v||"").trim().toLowerCase().replace(/[^a-z0-9-_ ]/g,"").replace(/\s+/g,"-").slice(0,30);}
const parse=v=>{try{return JSON.parse(v||'{}')}catch{return {}}};
export async function onRequestGet({request,env}){const user=await getCurrentUser(request,env);if(!user)return json({ok:false,error:"Not authenticated"},{status:401});const s=new URL(request.url).searchParams.get("server_id")||"";if(!await member(env,s,user.id))return json({ok:false,error:"Server not found"},{status:404});const rows=await env.DB.prepare(`SELECT id,server_id,name,position,topic,type,bitrate,user_limit,permissions_json FROM server_channels WHERE server_id=? ORDER BY position,created_at`).bind(s).all();return json({ok:true,channels:(rows.results||[]).map(r=>({...r,permissions:parse(r.permissions_json)}))});}
export async function onRequestPost({request,env}){const user=await getCurrentUser(request,env);if(!user)return json({ok:false,error:"Not authenticated"},{status:401});let d={};try{d=await request.json();}catch{}const s=String(d.server_id||""),m=await member(env,s,user.id);if(!m||!["owner","admin"].includes(m.role))return json({ok:false,error:"Missing permission"},{status:403});const name=cleanName(d.name);if(!name)return json({ok:false,error:"Channel name is required"},{status:400});const p=await env.DB.prepare(`SELECT COALESCE(MAX(position),-1)+1 p FROM server_channels WHERE server_id=?`).bind(s).first();const type=d.type==='voice'?'voice':'text',c={id:id("sch"),server_id:s,name,topic:String(d.topic||"").slice(0,160),position:Number(p?.p||0),type,bitrate:Math.max(8000,Math.min(128000,Number(d.bitrate)||64000)),user_limit:Math.max(0,Math.min(99,Number(d.user_limit)||0)),permissions:d.permissions||{}};await env.DB.prepare(`INSERT INTO server_channels(id,server_id,name,position,topic,type,bitrate,user_limit,permissions_json) VALUES(?,?,?,?,?,?,?,?,?)`).bind(c.id,s,name,c.position,c.topic,c.type,c.bitrate,c.user_limit,JSON.stringify(c.permissions)).run();return json({ok:true,channel:c});}
export async function onRequestPatch({request,env}){const user=await getCurrentUser(request,env);if(!user)return json({ok:false,error:"Not authenticated"},{status:401});let d={};try{d=await request.json();}catch{}const row=await env.DB.prepare(`SELECT sc.*,sm.role FROM server_channels sc JOIN server_members sm ON sm.server_id=sc.server_id AND sm.user_id=? WHERE sc.id=?`).bind(user.id,String(d.channel_id||"")).first();if(!row||!["owner","admin"].includes(row.role))return json({ok:false,error:"Missing permission"},{status:403});const name=cleanName(d.name??row.name);if(!name)return json({ok:false,error:"Channel name is required"},{status:400});const topic=String(d.topic??row.topic??"").slice(0,160),type=d.type==='voice'?'voice':(d.type==='text'?'text':row.type),bitrate=Math.max(8000,Math.min(128000,Number(d.bitrate??row.bitrate)||64000)),limit=Math.max(0,Math.min(99,Number(d.user_limit??row.user_limit)||0)),permissions=d.permissions??parse(row.permissions_json);await env.DB.prepare(`UPDATE server_channels SET name=?,topic=?,type=?,bitrate=?,user_limit=?,permissions_json=? WHERE id=?`).bind(name,topic,type,bitrate,limit,JSON.stringify(permissions),String(d.channel_id)).run();return json({ok:true,channel:{id:String(d.channel_id),server_id:row.server_id,name,topic,type,bitrate,user_limit:limit,permissions}});}
export async function onRequestDelete({request,env}){const user=await getCurrentUser(request,env);if(!user)return json({ok:false,error:"Not authenticated"},{status:401});let d={};try{d=await request.json();}catch{}const idv=String(d.channel_id||""),row=await env.DB.prepare(`SELECT sc.server_id,sm.role,(SELECT COUNT(*) FROM server_channels x WHERE x.server_id=sc.server_id AND x.type='text') text_count,sc.type FROM server_channels sc JOIN server_members sm ON sm.server_id=sc.server_id AND sm.user_id=? WHERE sc.id=?`).bind(user.id,idv).first();if(!row||!["owner","admin"].includes(row.role))return json({ok:false,error:"Missing permission"},{status:403});if(row.type==='text'&&Number(row.text_count)<=1)return json({ok:false,error:"A server must keep at least one text channel"},{status:400});await env.DB.prepare(`DELETE FROM server_channels WHERE id=?`).bind(idv).run();return json({ok:true,server_id:row.server_id,channel_id:idv});}
